server:
  port: 7854
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zntzhang/springcloud-config.git
          username: zntzhang
          password: zhangtao19941214
eureka:
  instance:
    hostname: localhost
    port: 7777
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
