server:
  port: 7779
spring:
  application:
    name: api
eureka:
  instance:
    hostname: localhost
    port: 7777
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/