server:
  port: 7778
spring:
  application:
    name: client
  datasource:
    username: root
    password: Zt123456!
    url: jdbc:mysql://120.55.53.207:3306/springcloud?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost
    port: 7777
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml